name: Waka Readme

on:
  schedule:
    - cron: '0 10,22 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Dev Logs
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_SHORT_INFO: false
          COMMIT_MESSAGE: "🤙🏻 Update dev logs"
          SHOW_UPDATED_DATE: false
          SHOW_LOC_CHART: false
